apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: froppyshima-back-deployment
  labels:
    app: froppyshima-back
spec:
  selector:
    matchLabels:
      app: froppyshima-back
  replicas: 1
  template:
    metadata:
      labels:
        app: froppyshima-back
    spec:
      containers:
      - name: froppyshima-back
        image: froppyshima-back
        imagePullPolicy: Never
        ports:
        - name: back-service
          containerPort: 3000
        env:
        - name: PORT
          value: '3000'
        - name: BOLT_DB_PATH
          value: '/froppyshima-db/froppyshimaDB'
        volumeMounts:
        - name: froppyshima-back-persistent-storage
          mountPath: /froppyshima-db/
      volumes:
      - name: froppyshima-back-persistent-storage
        persistentVolumeClaim:
          claimName: froppyshima-back-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: froppyshima-back-service
spec:
  type: NodePort
  selector:
    app: froppyshima-back
  ports:
  - port: 3000
    targetPort: back-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: froppyshima-front-deployment
  labels:
    app: froppyshima-front
spec:
  selector:
    matchLabels:
      app: froppyshima-front
  replicas: 1
  template:
    metadata:
      labels:
        app: froppyshima-front
    spec:
      containers:
      - name: froppyshima-front
        image: froppyshima-front
        imagePullPolicy: Never
        ports:
        - name: front-service
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: froppyshima-front-service
spec:
  type: NodePort
  selector:
    app: froppyshima-front
  ports:
  - port: 3000
    targetPort: front-service
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: froppyshima-back-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/froppyshima-data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: froppyshima-back-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
