version: '3.4'
services:
  back:
    build:
      context: ./back/
      target: release
    ports:
    - "127.0.0.1:8080:8080"
    environment:
      - BOLT_DB_PATH=/db/froppyshimaDB
    volumes:
       - bolt-db:/db
  web:
    build: ./web/
    ports:
    - "127.0.0.1:3000:80"
    depends_on:
      - back
volumes:
  bolt-db:
